### ISSUE TITLE
w.show() gives GraphWidget(layout=Layout(height='500px', width='100%')) instead of picture

### ISSUE THREAD

**Issue by tedhabermann** [yWorks/yfiles-jupyter-graphs#24]
**Describe the bug**
Running jupyterLab on mac: http://localhost:8889/lab

**To Reproduce**
Trying introduction.ipynb:
from yfiles_jupyter_graphs import GraphWidget
w = GraphWidget()
w

gives
GraphWidget(layout=Layout(height='500px', width='100%'))

**Comment by yGuy** [comment]
Hey - thanks for your feedback. I would be surprised if this was always the case. And since I cannot reproduce this, this is likely because something is different on your machine. Are you absolutely sure that after installing the package, you restarted the jupyter server? This typically is the output if there was not jupyter widgets installed, before. Jupyter needs a restart, then.

Also, it might be due to some incompatibilities with other packages. So please provide more information about your setup, with all the versions involved and also check whether there is error output on the console in the browser or the server logs.

Have you tried following the instructions with the docker install? This creates a clean build and works great (for me and others, at least). If you can get the docker image to run, you can try and compare what is different in your original setup.
