### ISSUE TITLE
Only 127.0.0.1 and localhost supported :(

### ISSUE THREAD

**Issue by paltusplintus** [yWorks/yfiles-jupyter-graphs#29]
**Describe the bug**
Getting a message:
"The widget only permits use on 127.0.0.1 and localhost. In case this doesn't work for you, let us know on [GitHub](https://github.com/yWorks/yfiles-jupyter-graphs/issues)."
When running the widget on https://go.dominodatalab.com/ 
platform.
It is common for companies to use platforms like Domino or Databricks to do jupyter notebooking, where host might be different. Is there a particular reason for this restriction? 
Thanks.

**Screenshots**
![image](https://user-images.githubusercontent.com/42695162/206704587-9b609514-1521-4385-8add-5e94db00485e.png)

**Desktop (please complete the following information):**
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
MS Edge browser

**Comment by yGuy** [comment]
Thanks. We are currently considering lifting this restriction and we will be white-listing more applications. 

Is "dominodatalab.com" part of the domain (window.location) when you see that message?
What would be the exact domain for "databricks"?

We are still hesitating to make this available for all domains. This is not for technical reasons, but purely commercial. See also: https://github.com/yWorks/yfiles-jupyter-graphs/discussions/28

**Comment by paltusplintus** [comment]
Thanks for your quick response and my compliments for a nice tool!
Domino host may vary from company to company as far as I understand. Most likely a mask like "https://domino*" should work fine. The structure of url to the notebook for me would look like
https://domino-dev.gsk.com/{username}/{project_name}/notebookSession/{run_id}/proxy/{port}/
But the -dev and .gsk part may vary depending on the company.

**Comment by fskpf** [comment]
With the latest release (v1.4.2), we added 'domino' to the allowed domains. So hopefully this should make it work on your end. In any case, please let us know.

**Comment by paltusplintus** [comment]
Thanks! It worked in Jupyter Notebook environment.
Noticed the following issue in Jupyter Lab with v1.4.2 though:
![image](https://user-images.githubusercontent.com/42695162/208403183-615aee60-53bf-4a75-9dc2-aa6b49cdfe46.png)

**Comment by yGuy** [comment]
This indicates that you need to restart the jupyter server, first. If you are absolutely sure that this also happens on a clean installation with a freshly started jupyter labs instance, please do get back and report more version details about the components you are using.

**Comment by fskpf** [comment]
@paltusplintus I noticed something similar while testing the updated widget in different environments:

In a https://mybinder.org/ environment, the widget worked in Jupyter Notebook but not in Jupyter Lab (although the error was different).

However, it fixed itself after [clearing the cache](https://superuser.com/questions/89809/how-to-force-refresh-without-cache-in-google-chrome) and reloading the MyBinder page. It was not sufficient to just restart the kernel and run the notebook again.

I think this may be caused by an 'inline' installation of the widget. For example, if you install the widget within a notebook cell like so
```
%pip install yfiles-jupyter-graphs
```
In this case, make sure to reload the browser page as well.

However, in other environments, it just works out of the box.
